services:
  # Backend API
  - type: web
    name: sorbonexus-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You'll need to set this manually in Render dashboard

  # Frontend
  - type: web
    name: sorbonexus-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://sorbonexus-backend.onrender.com # Update with your actual backend URL
